- name: 'Downloading 3CX pubkey' # wget http://downloads-global.3cx.com/downloads/3cxpbx/public.key
  ansible.builtin.get_url:
    url: http://downloads-global.3cx.com/downloads/3cxpbx/public.key
    dest: /root/

- name: 'Adding 3CX pubkey' # apt-key add
  ansible.builtin.apt_key:
    # url: http://downloads-global.3cx.com/downloads/3cxpbx/public.key
    file: /root/public.key
    state: present

- name: 'Adding 3CX Repo' # echo "deb http://downloads-global.3cx.com/downloads/debian buster main" | tee /etc/apt/sources.list.d/3cxpbc.list
  ansible.builtin.lineinfile:
    create: true
    path: /etc/apt/sources.list.d/3cxpbc.list
    line: "deb http://downloads-global.3cx.com/downloads/debian buster main"

- name: 'Update repositories'
  ansible.builtin.apt:
    update_cache: yes
#    name: "3cxpbx"
#    state: present
